wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708684460.369115
    t:
      1:
      - 5
      - 53
      - 55
      - 86
      - 95
      2:
      - 5
      - 53
      - 55
      - 86
      - 95
      3:
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
